// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice = CourseHeroSlice | ServiceSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Page Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *CourseHero → Default → Primary*
 */
export interface CourseHeroSliceDefaultPrimary {
  /**
   * Background Image field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Course Title White 1 field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.course_title_white_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  course_title_white_1: prismic.KeyTextField;

  /**
   * Course Title Highlight field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.course_title_highlight
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  course_title_highlight: prismic.KeyTextField;

  /**
   * Course Title White 2 field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.course_title_white_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  course_title_white_2: prismic.KeyTextField;

  /**
   * Description field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Duration field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.duration
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  duration: prismic.KeyTextField;

  /**
   * Delivery Type field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.delivery_type
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  delivery_type: prismic.KeyTextField;

  /**
   * Languages field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.languages
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  languages: prismic.KeyTextField;

  /**
   * Locations field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.locations
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  locations: prismic.KeyTextField;

  /**
   * Course Outline URL field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.course_outline_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  course_outline_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Enquire URL field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.enquire_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  enquire_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Bottom Link Text field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.bottom_link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bottom_link_text: prismic.KeyTextField;

  /**
   * Bottom Link URL field in *CourseHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: course_hero.default.primary.bottom_link_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  bottom_link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CourseHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CourseHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CourseHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CourseHero*
 */
type CourseHeroSliceVariation = CourseHeroSliceDefault;

/**
 * CourseHero Shared Slice
 *
 * - **API ID**: `course_hero`
 * - **Description**: CourseHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CourseHeroSlice = prismic.SharedSlice<
  "course_hero",
  CourseHeroSliceVariation
>;

/**
 * Item in *ServiceSection → Default → Primary → Service Items*
 */
export interface ServiceSectionSliceDefaultPrimaryServiceItemsItem {
  /**
   * Icon field in *ServiceSection → Default → Primary → Service Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.service_items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Service Title field in *ServiceSection → Default → Primary → Service Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.service_items[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service Description field in *ServiceSection → Default → Primary → Service Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.service_items[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  service_description: prismic.RichTextField;
}

/**
 * Primary content in *ServiceSection → Default → Primary*
 */
export interface ServiceSectionSliceDefaultPrimary {
  /**
   * Section Title field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Subtitle field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Service Items field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.service_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  service_items: prismic.GroupField<
    Simplify<ServiceSectionSliceDefaultPrimaryServiceItemsItem>
  >;
}

/**
 * Default variation for ServiceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceSection*
 */
type ServiceSectionSliceVariation = ServiceSectionSliceDefault;

/**
 * ServiceSection Shared Slice
 *
 * - **API ID**: `service_section`
 * - **Description**: ServiceSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSlice = prismic.SharedSlice<
  "service_section",
  ServiceSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CourseHeroSlice,
      CourseHeroSliceDefaultPrimary,
      CourseHeroSliceVariation,
      CourseHeroSliceDefault,
      ServiceSectionSlice,
      ServiceSectionSliceDefaultPrimaryServiceItemsItem,
      ServiceSectionSliceDefaultPrimary,
      ServiceSectionSliceVariation,
      ServiceSectionSliceDefault,
    };
  }
}
