// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  course_hero: dynamic(() => import("./CourseHero")),
  service_section: dynamic(() => import("./ServiceSection")),
};
